#!/bin/bash

ExeDir=`pwd -P`
echo "ExeDir is $(pwd)"

kill_server()
{
	pids=`ps aux | grep $ExeDir/$1 | grep -v "grep" | awk '{print $2}'`;
	if [ -n "$pids" ]; then
		for pid in $pids
		do
			echo "kill $ExeDir/$1 pid:$pid"
			kill $pid;
		done
		return 0;
	else
		echo "$1 no exist"
		return 0;
	fi
}

kill_server Session
echo "Session has been killed.."
sleep 2s

kill_server Gateway
echo "Gateway has been killed.."
sleep 2s

kill_server World
echo "World has been killed.."
sleep 2s
