--[[ConfDB.lua
描述:
	配置数据加载
--]]

require "data.MapDB"
require "data.SchoolPlayerDB"
require "data.WarrantDB"
require "data.MedicamentDB"
require "data.NpcDB.NpcDB"
require "data.NpcPackDB"
require "data.ExchangePropsDB"
require "data.EquipDB.EquipmentDB"
require "data.EquipDB.AddAttrTypeDB"
require "data.EquipDB.AddAttrValueDB"
require "data.EquipDB.BindAttrValueDB"
require "data.EquipDB.EquipMoneyConsumeDB"
require "data.EquipDB.EquipItemConsumeDB"
require "data.EquipDB.EquipRemouldDB"
require "data.EquipDB.EquipFormulaDB"
require "data.EquipDB.RefiningEffectDB"
require "data.EquipDB.ModelIDByClothDB"
require "data.OpenTreasureChestDB"
require "data.RideDB"
require "data.TaskDB.TaskDB"
require "data.TaskDB.LoopTaskRewardDB"
require "data.DialogDB.DialogModelDB"
require "data.DialogDB.NormalDialogModelDB"
require "data.DialogDB.GuideDialogModelDB"
require "data.PetDB"
require "data.EctypeDB.EctypeDB"
require "data.EctypeDB.RingEctypeDB"
require "data.EctypeDB.FactionEctypeDB"
require "data.EctypeDB.EctypeObjectDB"
require "data.TreasureDB.TreasureDB"
require "data.TreasureDB.TreasureEffectDB"
require "data.TreasureDB.TreasureEventDB"
require "data.TreasureDB.TreasureInMapDB"
require "data.PlayerLevelUpDB"
require "data.SkillDB.SchoolMindDB"
require "data.SkillDB.MindDB"
require "data.SkillDB.MindDataDB"
require "data.SkillDB.FightSkillDB"
require "data.SkillDB.FightSkillDataDB"
require "data.BuffDB.FightOutBuffDB"
require "data.BuffDB.BuffEffectValueDB"
require "data.MateriaCostDB"
require "data.UpSkillDB"
require "data.ItemProductDB"
require "data.RefineDB"
require "data.ExperienceDB.ExperienceCostDB"
require "data.ExperienceDB.ExperienceEffectDB"
require "data.ExperienceDB.ExperienceDB"
require "data.OnlineRewardWinDB"
require "data.NewRewardsDB"

require "data.DropDB"

require "data.PetStudyDB"
require "data.SkillDB.PetSkillDB"
require "data.SkillDB.PetSkillDataDB"
require "data.PetSkillLevelUpDB"
require "data.CollectionDB"
require "data.ArticlesDB"
require "data.MonsterDB"
require "data.MonsterDropsDB"
require "data.ScriptFightDB"
require "data.WorldDropsDB"
require "data.ServerLevelDB"
-- 活动
require "data.ActivityDB.ActivityPageDB.ActivityPageDaliyDB"
require "data.ActivityDB.ActivityPageDB.ActivityPageDaliyDB"
require "data.ActivityDB.BeastBlessDB.BeastBlessInMapDB"
require "data.ActivityDB.BeastBlessDB.BeastBlessRewardDB"
require "data.ActivityDB.CatchPetDB.CatchPetDB"
require "data.ActivityDB.CatchPetDB.WayDB"

-- require "data.PetStudyDB"
-- require "data.SkillDB.PetSkillDB"
-- require "data.SkillDB.PetSkillDataDB"


