#!/bin/bash
#
#添加用户，删除用户命令
#

declare -a userNameArr=(devel zhaolu lijie jialun kanglijuan klj)
declare -a argv=$@
group=devel

if [ "$1" == "add" ]; then
	egrep "^$group" /etc/group >& /dev/null
	if [ $? -ne 0 ] ; then
		echo $group用户组不存在，先创建$group
    	groupadd $group
	fi

	if [ "$2" == "--def" ]; then
		for name in ${userNameArr[@]}
		do
			id $name >& /dev/null
			if [ $? -ne 0 ] ; then
				useradd -g $group $name
			else
				echo $name"already exists"
   			fi
		done
	elif [ "$2" == "--name" ]; then
		i=0
		for name in $argv
		do
			let i++
			if [ "$i" -ge "3" ]; then
				id $name >& /dev/null
				if [ $? -ne 0 ] ; then
					useradd -g $group $name
				else
					echo $name"already exists"
   				fi
			fi
		done
		unset argv
	else
		echo 参数错误，查看命令输入参数 --help
		exit
	fi
elif [ "$1" == "del" ]; then
	if [ "$2" == "--all" ]; then
		users=`cat /etc/passwd | awk -F: '$3 >= 501 && $3 < 1000 {print $1}'`
		echo $users
		for name in $users
		do
			echo $name
			userdel -r $name
		done
	elif [ "$2" == "--def" ]; then
		for name in ${userNameArr[@]}
		do
			echo $name
			userdel -r $name
		done
	elif [ "$2" == "--name" ]; then
		i=0
		for name in $argv
		do
			let i++
			if [ "$i" -ge "3" ]; then
				echo $name
				userdel -r $name
			fi
		done
		unset argv
	else
		echo 参数错误，查看命令输入参数 --help
	fi
elif [ "$1" == "--help" ]; then
	echo add --def 默认添加${userNameArr[@]}这些用户
	echo add -- name A B C ... 把A,B,C等后面有多少个用户名都添加成用户
	echo del -- def 默认删除${userNameArr[@]}这里所有的用户
	echo del --all 删除所有devel中的用户
	echo del --name A B C ...删除所有--name后面的参数
else
	echo 参数错误，查看命令输入参数 --help
	exit
fi
