#!/bin/bash
#
# 查看xxx.mak文件中的变量值
#

if [ "$#" -eq "1" ]; then
	echo ''
	cd ../mak.d; echo 'WORK_DIR = '$(pwd);
	cd ../mak.d; make -f $1 -f debug.mak PROJECT_NAME
	cd ../mak.d; make -f $1 -f debug.mak PROJECT_TYPE
	cd ../mak.d; make -f $1 -f debug.mak MACROS
	cd ../mak.d; make -f $1 -f debug.mak SRC_DIR
	cd ../mak.d; make -f $1 -f debug.mak INT_DIR
	cd ../mak.d; make -f $1 -f debug.mak TARGET_PATH
	cd ../mak.d; make -f $1 -f debug.mak _L_OP
	cd ../mak.d; make -f $1 -f debug.mak _C_OP
else
	echo "please provided MakeFileName."
	exit
fi
