#!/bin/bash
#
# cpu的逻辑数量 = cpu个数 * cpu核数 * 超线程个数
#
#

CurDir=`pwd`
echo "--current dir is : $(pwd)"
echo ""

cpu_count=`cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l`

cpu_per_cores=`cat /proc/cpuinfo | grep "cpu cores" | uniq | sed 's/^.*\([0-9]\{1,\}\)/\1/g'`

cpu_logic_num=`cat /proc/cpuinfo | grep "processor" | wc -l`

echo "--cpu info is below : "
echo "	cpu count is : $cpu_count"
echo "	cpu cores is : $(($cpu_count*$cpu_per_cores))"
echo "	cpu logic number is : $cpu_logic_num"

echo ""
read -p "Press any key to exit.." ret
